

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:nginx, applications, sync, default/nginx, allow
    p, role:nginx, applications, get, default/nginx, allow
    p, role:nginx, applications, delete, default/nginx, allow
    g, motoskia, role:nginx
    p, role:argocd-tomorrow, applications, get, self-service/argocd-tomorrow, allow
    p, role:argocd-tomorrow, applications, sync, self-service/argocd-tomorrow, allow
    p, role:argocd-tomorrow, applications, delete, self-service/argocd-tomorrow, allow
    g, tomorrow, role:argocd-tomorrow
    p, role:argocd-murugan, applications, get, self-service/argocd-murugan, allow
    p, role:argocd-murugan, applications, sync, self-service/argocd-murugan, allow
    p, role:argocd-murugan, applications, delete, self-service/argocd-murugan, allow
    g, murugan, role:argocd-murugan