apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:nginx, applications, sync, default/nginx, allow
    p, role:nginx, applications, get, default/nginx, allow
    p, role:nginx, applications, delete, default/nginx, allow
    g, motoskia, role:nginx
    p, role:argocd-tomorrow, applications, get, self-service/argocd-tomorrow, allow
    p, role:argocd-tomorrow, applications, sync, self-service/argocd-tomorrow, allow
    p, role:argocd-tomorrow, applications, delete, self-service/argocd-tomorrow, allow
    g, tomorrow, role:argocd-tomorrow
    p, role:argocd-murugan, applications, get, self-service/argocd-murugan, allow
    p, role:argocd-murugan, applications, sync, self-service/argocd-murugan, allow
    p, role:argocd-murugan, applications, delete, self-service/argocd-murugan, allow
    g, murugan, role:argocd-murugan
    p, role:argocd-prabhakar, applications, get, self-service/argocd-prabhakar, allow
    p, role:argocd-prabhakar, applications, sync, self-service/argocd-prabhakar, allow
    p, role:argocd-prabhakar, applications, delete, self-service/argocd-prabhakar, allow
    g, prabhakar, role:argocd-prabhakar
    p, role:argocd-test, applications, get, self-service/argocd-test, allow
    p, role:argocd-test, applications, sync, self-service/argocd-test, allow
    p, role:argocd-test, applications, delete, self-service/argocd-test, allow
    g, test, role:argocd-test
    p, role:argocd-today, applications, get, self-service/argocd-today, allow
    p, role:argocd-today, applications, sync, self-service/argocd-today, allow
    p, role:argocd-today, applications, delete, self-service/argocd-today, allow
    g, today, role:argocd-today
    p, role:argocd-tomorrow, applications, get, self-service/argocd-tomorrow, allow
    p, role:argocd-tomorrow, applications, sync, self-service/argocd-tomorrow, allow
    p, role:argocd-tomorrow, applications, delete, self-service/argocd-tomorrow, allow
    g, tomorrow, role:argocd-tomorrow
    p, role:argocd-dea, applications, get, self-service/argocd-dea, allow
    p, role:argocd-dea, applications, sync, self-service/argocd-dea, allow
    p, role:argocd-dea, applications, delete, self-service/argocd-dea, allow
    g, dea, role:argocd-dea
    p, role:argocd-yesterday, applications, get, self-service/argocd-yesterday, allow
    p, role:argocd-yesterday, applications, sync, self-service/argocd-yesterday, allow
    p, role:argocd-yesterday, applications, delete, self-service/argocd-yesterday, allow
    g, yesterday, role:argocd-yesterday
    p, role:argocd-monday, applications, get, self-service/argocd-monday, allow
    p, role:argocd-monday, applications, sync, self-service/argocd-monday, allow
    p, role:argocd-monday, applications, delete, self-service/argocd-monday, allow
    g, monday, role:argocd-monday
    p, role:argocd-july, applications, get, self-service/argocd-july, allow
    p, role:argocd-july, applications, sync, self-service/argocd-july, allow
    p, role:argocd-july, applications, delete, self-service/argocd-july, allow
    g, july, role:argocd-july
    p, role:argocd-june, applications, get, self-service/argocd-june, allow
    p, role:argocd-june, applications, sync, self-service/argocd-june, allow
    p, role:argocd-june, applications, delete, self-service/argocd-june, allow
    g, june, role:argocd-june