apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:nginx, applications, sync, default/nginx, allow
    p, role:nginx, applications, get, default/nginx, allow
    p, role:nginx, applications, delete, default/nginx, allow
    g, motoskia, role:nginx
    p, role:argocd-prabhakar, applications, get, self-service/argocd-prabhakar, allow
    p, role:argocd-prabhakar, applications, sync, self-service/argocd-prabhakar, allow
    p, role:argocd-prabhakar, applications, delete, self-service/argocd-prabhakar, allow
    g, prabhakar, role:argocd-prabhakar
    g, dea, role:argocd-prabhakar
    g, india, role:argocd-prabhakar
    p, role:argocd-motoskia, applications, get, self-service/argocd-motoskia, allow
    p, role:argocd-motoskia, applications, sync, self-service/argocd-motoskia, allow
    p, role:argocd-motoskia, applications, delete, self-service/argocd-motoskia, allow
    g, /motoskia, role:argocd-motoskia
    g, /foxutech, role:argocd-motoskia
