apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:nginx, applications, sync, default/nginx, allow
    p, role:nginx, applications, get, default/nginx, allow
    p, role:nginx, applications, delete, default/nginx, allow
    g, motoskia, role:nginx
    p, role:argocd-june, applications, get, self-service/argocd-june, allow
    p, role:argocd-june, applications, sync, self-service/argocd-june, allow
    p, role:argocd-june, applications, delete, self-service/argocd-june, allow
    g, june, role:argocd-june    g,  /prabu, role:argocd-june    g,  /motoskia, role:argocd-june
    p, role:argocd-diya, applications, get, self-service/argocd-diya, allow
    p, role:argocd-diya, applications, sync, self-service/argocd-diya, allow
    p, role:argocd-diya, applications, delete, self-service/argocd-diya, allow
    g, diya, role:argocd-diya
    p, role:argocd-june, applications, get, self-service/argocd-june, allow
    p, role:argocd-june, applications, sync, self-service/argocd-june, allow
    p, role:argocd-june, applications, delete, self-service/argocd-june, allow
    g, june, role:argocd-june
    g,  /prabu, role:argocd-june
    g,  /motoskia, role:argocd-june
    p, role:argocd-diya, applications, get, self-service/argocd-diya, allow
    p, role:argocd-diya, applications, sync, self-service/argocd-diya, allow
    p, role:argocd-diya, applications, delete, self-service/argocd-diya, allow
    g, diya, role:argocd-diya
